### ISSUE TITLE
Work towards creating streams

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-config#100]
So, we're now in a position where we can start implementing the stream work as described in https://github.com/coreos/fedora-coreos-tracker/blob/master/stream-tooling.md.

I'd like to suggest the following concrete steps to start:
- [x] rename `master` to `testing-devel`
- [x] add two new branches: `testing` and `bodhi-updates`, which are copies of `testing-devel` modulo the `ref` (we can manually keep `bodhi-updates` in sync to start, but need to work towards automating this)
- [x] set up pipeline for periodic `bodhi-updates` runs (basically what it does today, but targeting the new stream)
- [ ] push output lockfile to the `bodhi-updates` branch (see https://github.com/coreos/coreos-assembler/pull/553) (again, can start manually to get things going, but need to automate this very soon)
- [ ] for now, just push lockfile to `testing-devel` as well; we can work towards making this a PR-based + CI workflow afterwards
- [ ] hook up `coreos-koji-tagger` to watch `testing-devel`
- [x] set up pipelines for `testing-devel` and `testing` runs triggered on ref changes
- [ ] try out `testing` releases by manually merging from the `testing-devel` branch using the mythical "theirs" strategy, and work on tooling to make this less manual & error-prone.

All open for discussions of course. The goal is to get a taste of the workflow across mechanical, devel, and prod streams even if in a semi-manual capacity and unblock tooling and automation work. Once we have this down, we can start filling in more of the blanks, such as working towards automation for doing a `testing` release, adding the remaining prod, devel, and mechanical streams, etc...

**Comment by jlebon** [comment]
> add two new branches: `testing` and `bodhi-updates`, which are copies of `testing-devel` modulo the `ref`

Minor prep for this in: https://github.com/coreos/fedora-coreos-config/pull/101

**Comment by dustymabe** [comment]
seems reasonable to me 

> rename master to testing-devel

so we no longer have a master branch at all? let me know when we do this and we can change the settings in this repo to have everything act correctly.

**Comment by jlebon** [comment]
> so we no longer have a master branch at all?

Right. All our development would happen on the `testing-devel` stream, but it'd be confusing to have just that one have a branch name that doesn't match the stream name.

**Comment by dustymabe** [comment]
> but it'd be confusing to have just that one have a branch name that doesn't match the stream name.

agree

**Comment by dustymabe** [comment]
related: https://github.com/coreos/fedora-coreos-tracker/issues/180

**Comment by jlebon** [comment]
> 1. rename master to testing-devel

This has happened now (though it's more of a copy and delete since git doesn't actually have a "remote ref rename" concept).

> 2. add two new branches: `testing` and `bodhi-updates`, which are copies of testing-devel modulo the ref (we can manually keep bodhi-updates in sync to start, but need to work towards automating this)

https://github.com/coreos/fedora-coreos-config/pull/103
https://github.com/coreos/fedora-coreos-config/pull/104

**Comment by jlebon** [comment]
If your git checkout is throwing weird errors looking for master, try `git fetch upstream --prune` then `vim .git/refs/remotes/upstream/HEAD` and do a `s/master/testing-devel/`.

**Comment by jlebon** [comment]
> - [x] set up pipeline for periodic bodhi-updates runs (basically what it does today, but targeting the new stream)
> - [x] set up pipelines for testing-devel and testing runs triggered on ref changes

These are done by https://github.com/coreos/fedora-coreos-pipeline/pull/76 now.

I think now we should split out the various bits of automation required into separate tickets and swarm on those?

**Comment by dustymabe** [comment]
> I think now we should split out the various bits of automation required into separate tickets and swarm on those?

SGTM

**Comment by jlebon** [comment]
OK started with https://github.com/coreos/fedora-coreos-tracker/issues/204 and https://github.com/coreos/fedora-coreos-tracker/issues/205.

**Comment by cgwalters** [comment]
I think this is all done.
