### ISSUE TITLE
Drop `coreos-cleanup-ignition-config.service` after the next barrier release on all streams

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-config#1094]
Ignition will now automatically remove `/boot/ignition` on first boot, so `coreos-cleanup-ignition-config.service` only needs to handle old nodes.  Once all of those have passed through a barrier, we can revert #1093.

For https://github.com/coreos/fedora-coreos-tracker/issues/889.

**Comment by dustymabe** [comment]
Should we add this to the checklist in https://github.com/coreos/fedora-coreos-tracker/issues/884 ?

**Comment by bgilbert** [comment]
@dustymabe Done.
