### ISSUE TITLE
What if I really want to include the python3 package?

### ISSUE THREAD

**Issue by fengye87** [coreos/fedora-coreos-config#1165]
I can see that python is excluded for purpose, but what if I really want to ship it within images? I found it impossible to use ansible if python is missing in the target host.

**Comment by dustymabe** [comment]
In the future please ask questions like this on our [discussion forum](https://discussion.fedoraproject.org/c/server/coreos/5).

you're free to package layer it if you want (`sudo rpm-ostree install`), but we don't recommend it as you introduce host dependencies that your applications depend on that could break with automatic updates.
