### ISSUE TITLE
tests: break up misc-ro and misc-ign-ro into individually scoped tests

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-config#1228]
Now that we support combining non-exclusive tests into a single VM let's break up misc-ro and misc-ign-ro into their own test directories (specific focus/scope with better documentation for rationale) and mark then as `exclusive: false`.

**Comment by dustymabe** [comment]
@mike-nguyen @aaradhak - did we do this one?

**Comment by aaradhak** [comment]
> 

I dont think this is done yet.

**Comment by dustymabe** [comment]
hmm - but those files don't exist any more in the repo. I think it was taken care of by f50f500 and 1e2e2a7

**Comment by mike-nguyen** [comment]
Yes this is done.  Ash did the standardizing of the test formats after I did the break up.  I'll close this issue if there are no objections.
