### ISSUE TITLE
tests: identify and mark non-exclusive tests

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-config#1229]
Now that we support combining non-exclusive tests into a single VM let's identify other tests that we have written in our external tests within this repo (other than `misc-ro` and `misc-ign-ro`) that aren't exclusive and can be marked as `exclusive: false`).

**Comment by saqibali-2k** [comment]
The general workflow here is: 

- Find a test that you think is non-exclusive and modify the kola.json file or tag with a `exclusive: false` key-value.
- Run non-exclusive tests to verify that tests are still passing and that the test we changed is non-exclusive 

Reminder: we can use `cosa kola run <blob pattern>` to run a specific test or a group of tests.

**Comment by Adam0Brien** [comment]
no additional tests needed to be marked as exclusive false
