### ISSUE TITLE
s390x: /usr/lib/s390-tools/cpictl is installed group-writable

### ISSUE THREAD

**Issue by jschintag** [coreos/fedora-coreos-config#1551]
Currently the test ext.config.files.file-directory-permissions is failing on s390x because `/usr/lib/s390-tools/cpictl` is installed group-writable.
This is a problem with the rpm and already fixed in version 2.19.0.
https://github.com/ibm-s390-linux/s390-tools/pull/124
More details can also be found here https://bugzilla.redhat.com/show_bug.cgi?id=2024102

**Comment by miabbott** [comment]
We're snoozing the affected test for RHCOS in https://github.com/openshift/os/pull/733

**Comment by jschintag** [comment]
Closing as RHCOS includes the fixed version of s390utils and the temporary fix has been removed from RHCOS manifests
