### ISSUE TITLE
s390x: clhm.ignition-warnings test is failling because fetching ignition via virtio block device is still experimental

### ISSUE THREAD

**Issue by jschintag** [coreos/fedora-coreos-config#1713]
The clhm.ignition-warnings test is currently failling on s390x, because ignition emits a warning that fetching the ignition config via virtio block device is an experimental feature. Since the test only expects it's own artificially generated warning, it fails.
```
May 04 17:32:50 qemu0 systemd[1]: Started kola-runext.service.
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + . /var/opt/kola/extdata/commonlib.sh
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + WARN='\033[0;33m'
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + RESET='\033[0m'
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + warningsfile=/etc/issue.d/30_coreos_ignition_warnings.issue
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: ++ mktemp -d
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + tmpd=/tmp/tmp.XCplV6qegT
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + expectedwarningsfile=/tmp/tmp.XCplV6qegT/expectedwarningsfile
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + test -f /etc/issue.d/30_coreos_ignition_warnings.issue
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + echo -e '\033[0;33mIgnition: warning at $.systemd.units.0.contents: unit "echo.service" is enabled, but has no install section so enable does nothing\033[0m'
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + diff /tmp/tmp.XCplV6qegT/expectedwarningsfile /etc/issue.d/30_coreos_ignition_warnings.issue
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: 0a1
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: > Ignition: Fetching the Ignition config via the Virtio block driver is currently experimental and subject to change.
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + fatal 'Ignition warning did not show up as expected in issue.d'
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + echo 'Ignition warning did not show up as expected in issue.d'
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: Ignition warning did not show up as expected in issue.d
May 04 17:32:50 qemu0 kola-runext-test.sh[2114]: + exit 1
May 04 17:32:50 qemu0 systemd[1]: kola-runext.service: Main process exited, code=exited, status=1/FAILURE
May 04 17:32:50 qemu0 systemd[1]: kola-runext.service: Failed with result 'exit-code'.
```
There is already a PR to move the feature from the experimental stage, but it is a draft +2 years.
https://github.com/coreos/ignition/pull/999
What is the current plan in regards to this?
Or rather does it makes sense to adapt the testcase or go forward with moving it from experimental, since it has been working for years?

**Comment by dustymabe** [comment]
For this particular test we are trying to verify that the warning we expect gets surfaced to CLHM. What we don't account for is that other warnings may also be in the CLHM (this doesn't happen on x86_64 and aarch64).

We can adapt the test to be less strict about warnings showing up that we don't expect.. Or we could adapt the test to expect a different output on ppc64le and s390x qemu.

**Comment by jschintag** [comment]
I will take a look at it tomorrow. I'm leaning towards making the test ignore other warnings, that way it is more resillient to changes.

**Comment by cgwalters** [comment]
I don't understand why Ignition is warning here - why is the virtio thing still experimental?  Us emitting warnings about something *the user didn't in any way do* is just going to lead to confusion and concern on their part.

**Comment by dustymabe** [comment]
> I don't understand why Ignition is warning here - why is the virtio thing still experimental? Us emitting warnings about something _the user didn't in any way do_ is just going to lead to confusion and concern on their part.

We should probably drive to a conclusion in https://github.com/coreos/ignition/pull/999

**Comment by dustymabe** [comment]
Should issues like this be opened against the top level issue tracker? If agreed I'll move it over there.

**Comment by jschintag** [comment]
Here is the promised PR to improve the test #1715 for now
