### ISSUE TITLE
Find a safer alternative to check unit status

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-config#1743]
The following code in tests will always return true if the unit does not exists:
```
if [ $(systemctl show -p Result kdump.service) != "Result=success" ]; then
```

Thus we need a safer / smarter way to check this value.

See https://github.com/coreos/fedora-coreos-config/pull/1742#discussion_r873326178

**Comment by HuijingHei** [comment]
Thanks @dustymabe for the review, close this as https://github.com/coreos/fedora-coreos-config/pull/1989 merged
