### ISSUE TITLE
Add kola test to check for initrd udev rules

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-config#1775]
The initrd includes cloud-specific udev rules for at least AWS and Azure that, if omitted from the image, will cause certain Ignition configs to fail ([example](https://bugzilla.redhat.com/show_bug.cgi?id=2092966)).  We don't have kola CI on some of those clouds, and even when we do, may not have kola tests that use the specific device aliases created by these rules.

Since the rules files might move between packages/repos or disappear from a package/repo entirely, let's add a kola test that checks whether we're shipping the rules in the image.  It won't check the functionality of the rules, but we don't maintain them ourselves, so that seems reasonable.

The existing `ext.config.files.dracut-executable` test might be a good starting point.  `lsinitrd --unpack` or `coreos-installer dev extract initrd` can be used to unpack the initrd contents.

The test should be run on both FCOS and RHCOS.

**Comment by prestist** [comment]
This has been closed. The test was added [here](https://github.com/coreos/fedora-coreos-config/pull/1807).
