### ISSUE TITLE
Stop excluding `cowsay`

### ISSUE THREAD

**Issue by CheekyFresh** [coreos/fedora-coreos-config#1802]
Cowsay is a [useful tool](https://github.com/ansible/ansible/blob/5e369604e1930b1a2e071fecd7ec5276ebd12cb1/lib/ansible/utils/display.py#L445) for reading (especially long) event streams.  It is hilarious, however, to see it in this list. :laughing: 

https://github.com/coreos/fedora-coreos-config/blob/22555a454bf17aefb1f443e555a764789627ea05/manifests/fedora-coreos.yaml#L121

**Comment by bgilbert** [comment]
PRs welcome! :cow:

**Comment by jlebon** [comment]
Note that directive in the manifest doesn't prevent you from layering it. It's only an issue if you're rebuilding FCOS from scratch. In that case, you could remove it. And you'd have to remove `perl` as well from the list, which I'd be less OK with removing from this list. :)

**Comment by cgwalters** [comment]
I added it as a joke basically but I think given the above comment, there's not a real problem here so closing - but without any prejudice; if there's reason to actually change this we obviously can.
