### ISSUE TITLE
bad permissions on /etc/sudoers.d/coreos-sudo-group

### ISSUE THREAD

**Issue by grant-cl** [coreos/fedora-coreos-config#1872]
HI this file is still throwing an exception due to permissions

[manifest.yaml](https://github.com/bgilbert/os/blob/fea5b2a7671695ca2bfe93a9056fbe88b595ed40/manifest.yaml)
``` 
# Make security scanners happy
  # https://bugzilla.redhat.com/show_bug.cgi?id=1981979
  - |
    #!/usr/bin/env bash
    set -xeuo pipefail
    chmod 600 /etc/sudoers.d/*
```

Set it to 0600 but perms expected to 0440

# visudo -c
/etc/sudoers: parsed OK
/etc/sudoers.d/coreos-sudo-group: bad permissions, should be mode 0440

**Comment by bgilbert** [comment]
Good catch, thanks.  Note that you've linked to a draft version of the downstream RHCOS change, which never merged; the real culprit is [here](https://github.com/coreos/fedora-coreos-config/blob/ab890a4a25c0aa9761d8f9f695a5be8388697d30/overlay.d/05core/statoverride).
