### ISSUE TITLE
replace glibc-all-langpacks with glibc-minimal-langpack

### ISSUE THREAD

**Issue by juhp** [coreos/fedora-coreos-config#194]
Currently Fedora coreos installs all glibc locales (glibc-all-langpacks) which takes up a lot of space (~200MB on disk).

Since the default system locale is C.UTF-8 and default shell uses POSIX (it would be better to use C.UTF-8), how about just installing `glibc-minimal-langpack` instead of glibc-all-langpacks to save space and bandwidth: this is also what we do now in fedora base containers.

**Comment by ajeddeloh** [comment]
I'm all for minimizing the image. I think this would also be a good case for package layering if folks need other locales, but we should document it.

**Comment by dustymabe** [comment]
I think we did something in atomic host to strip out extra languages but I forget exactly.. Tagging in @jlebon to see if he recalls.

**Comment by bgilbert** [comment]
Container Linux does this and I've never been thrilled by it.  I'd rather we do our best to support speakers of non-English languages if possible.

**Comment by lucab** [comment]
I'm going to steal this ticket discussion to argue for a larger topic.

@bgilbert I don't disagree with supporting other languages to some extents (e.g. layering), but I actually like Container Linux approach (and this proposal).
I would like us to be opinionated and recommend (via docs and defaults) our stances on the following things:
 * UTC as the default node timezone
 * UTF-8 as the default node encoding
 * POSIX (i.e. English, C) as the default node locale

We then ship the minimum required to support this. Other bits can be bolted on top via package layering, like any other thing that diverge from our opinions/recommendations.

**Comment by jlebon** [comment]
> I think we did something in atomic host to strip out extra languages but I forget exactly.. Tagging in @jlebon to see if he recalls.

Sorry, forgot to get back to this.

It used to be more complex, but nowadays we can just do: https://pagure.io/fedora-atomic/blob/950eca4011488f8aaf6a4487f4aab7617319f9c5/f/fedora-atomic-host.json#_18. So e.g. to ship just `en_US`:

```yaml
install-langs:
  - en_US
```

**Comment by lucab** [comment]
@jlebon what's the result of that, under the hood? Is that better/worse than switching to the `-minimal` package?

**Comment by jlebon** [comment]
> @jlebon what's the result of that, under the hood? Is that better/worse than switching to the `-minimal` package?

It essentially sets the `_install_langs` RPM macro, which determines which translations get installed in `/usr/share/locale`. glibc also used to react to this by trimming the locales it installed, but this was dropped now that Fedora switched to subpackages: https://src.fedoraproject.org/rpms/glibc/c/50bcae98df7d383733d4d6d896b9e1e829914eb0. So I think we want to do both.

**Comment by jlebon** [comment]
FCOS now ships `glic-minimal-langpack` so I think this is done. We do not currently do any locale filtering on top of that (via `_install_langs`).
