### ISSUE TITLE
adjust buildroot container to work same as cosa

### ISSUE THREAD

**Issue by cgwalters** [coreos/fedora-coreos-config#1950]
This issue has a high overlap with https://github.com/coreos/fedora-coreos-tracker/issues/1289 

We moved the coreos-assembler build into the FCOS pipeline and it's now manifest listed etc., which is cool!

But our buildroot container which is used by many of our upstream project's CI also probably wants to be built in the same way.  Apparently we broke syncing from registry.ci to quay.io due to deleting a secret, so it'd help if we built "all" of our containers in the same way.

**Comment by dustymabe** [comment]
Do we need this built for more than x86_64? It's currently not today. I'm fine to add other architectures, but I prefer to not do that unless something is actually using it. Of course, it would a few line change to add those other architectures in the future.

**Comment by dustymabe** [comment]
Fix over in https://github.com/coreos/fedora-coreos-pipeline/pull/622

**Comment by dustymabe** [comment]
and the first build has landed in quay: https://quay.io/repository/coreos-assembler/fcos-buildroot?tab=tags

Can someone confirm it's working as expected for them?

**Comment by cgwalters** [comment]
https://github.com/openshift/release/pull/32029

**Comment by dustymabe** [comment]
Thank you Colin!
