### ISSUE TITLE
selinux issue during compose

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-config#22]
Jonathan reported this to me the other day and I'm now seeing it too in the FCOS pipeline running in centos CI.

```
lvm2.post: rpm-ostree-systemctl: Ignored non-preset command: enable lvm2-monitor.service
lvm2.post: rpm-ostree-systemctl: Ignored non-preset command: enable lvm2-lvmetad.socket
lvm2.post: rpm-ostree-systemctl: Ignored non-preset command: enable lvm2-lvmpolld.socket
chrony.post: rpm-ostree-systemctl: Ignored non-preset command: daemon-reload

66 done
Writing rpmdb... error: Plugin selinux: hook tsm_pre failed
[31m[1merror: [22m[0mFailed to update rpmdb (rpmtsRun code -1)

```

Not really sure what's going on yet and haven't had a chance to try to repro locally not in a supermin VM, but figured I would open the issue to track. I don't know if the issue is in Fedora or in CoreOS Assembler (my branch with supermin code). We'll move it if we need to.

**Comment by dustymabe** [comment]
ok I can verify that I can reproduce this locally (not just in jenkins on openshift on centos ci) when using a supermin VM. Need to check taking the VM out of the equation.

**Comment by dustymabe** [comment]
ok tried without the VM with the latest in upstream coreos-assembler (scripts) and I don't see an issue: 

```
lvm2.post: rpm-ostree-systemctl: Ignored non-preset command: enable lvm2-monitor.service                                                                                                                     
lvm2.post: rpm-ostree-systemctl: Ignored non-preset command: enable lvm2-lvmetad.socket                                                                                                                      
lvm2.post: rpm-ostree-systemctl: Ignored non-preset command: enable lvm2-lvmpolld.socket
chrony.post: rpm-ostree-systemctl: Ignored non-preset command: daemon-reload
66 done
Writing rpmdb... done
Relabeling (392/392) [=============] 100%

```

so.. the investigation continues

**Comment by cgwalters** [comment]
Well it's clearly related to supermin.  Does it mount `/sys/fs/selinux` by default?   Is `selinux-policy-targeted` being installed even?

Offhand looking at the code, I bet it would work to pass `RPMTRANS_FLAG_NOCONTEXTS` in rpm-ostree.  We actually don't want anything to do with the RPM SELinux plugin in rpm-ostree.

**Comment by cgwalters** [comment]
https://github.com/projectatomic/rpm-ostree/pull/1647

**Comment by cgwalters** [comment]
(I tested it doesn't break anything, but I didn't test it fixes this issue either)

**Comment by jlebon** [comment]
Heh, it's funny I was discussing with Dusty about this issue and finally remembered where I hit this before: https://bugzilla.redhat.com/show_bug.cgi?id=1493267.

> Does it mount /sys/fs/selinux by default? Is selinux-policy-targeted being installed even?

Given the above issue, I agree that's likely the issue. Let me try it out with https://github.com/projectatomic/rpm-ostree/pull/1647.

**Comment by jlebon** [comment]
Yup, that fixes it for me! Still unclear though why it previously worked and then recently stopped working.

**Comment by dustymabe** [comment]
i think we can consider this fixed now since a fix merged upstream: https://github.com/projectatomic/rpm-ostree/pull/1647
