### ISSUE TITLE
Compose an ostree commit by rpm-ostree failed

### ISSUE THREAD

**Issue by chintzung** [coreos/fedora-coreos-config#2418]
I followed https://coreos.github.io/rpm-ostree/compose-server/#running-rpm-ostree-compose-tree
to perform a local build of CoreOS. 
it results in failure, error message: "error: Copying ostree layers from target repo into build repo: Failed to pull-local overlay/06el9: Refspec 'overlay/06el9' not found"

Steps:

# Clone the config
git clone https://github.com/coreos/fedora-coreos-config.git && cd fedora-coreos-config

# Prepare directories
mkdir -p repo cache
ostree --repo=repo init --mode=archive

# Build (compose) 
sudo rpm-ostree compose tree --repo=repo --cachedir=cache manifest.yaml

Does anyone know the reason for this issue? How should it be resolved? Or did I make a mistake at some step?

Thank you.

**Comment by cgwalters** [comment]
Hi yes, it's because coreos-assembler has a bit of logic on top of rpm-ostree.  See https://github.com/coreos/coreos-assembler/blob/main/docs/building-fcos.md
