### ISSUE TITLE
mount generators fail when rebased from Atomic Host/Silverblue

### ISSUE THREAD

**Issue by mildred** [coreos/fedora-coreos-config#243]
This is probably an unsupported migration path, but I have a system that was running fedora silverblue, planning to rebase it to fedora coreos afterwards. I rebased it today and I have issues with /boot not mounting properly.

Actually, the file `/run/systemd/generator/boot.mount` is empty.

I debugged coreos-boot-mount-generator (by adding some shell debugging at the top of the file) and I get the following log and error:

```
+ cat /proc/mounts
sysfs /sys sysfs rw,seclabel,nosuid,nodev,noexec,relatime 0 0
proc /proc proc rw,nosuid,nodev,noexec,relatime 0 0
devtmpfs /dev devtmpfs rw,seclabel,nosuid,size=1899000k,nr_inodes=474750,mode=755 0 0
securityfs /sys/kernel/security securityfs rw,nosuid,nodev,noexec,relatime 0 0
tmpfs /dev/shm tmpfs rw,seclabel,nosuid,nodev 0 0
devpts /dev/pts devpts rw,seclabel,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000 0 0
tmpfs /run tmpfs rw,seclabel,nosuid,nodev,mode=755 0 0
tmpfs /sys/fs/cgroup tmpfs ro,seclabel,nosuid,nodev,noexec,mode=755 0 0
cgroup2 /sys/fs/cgroup/unified cgroup2 rw,seclabel,nosuid,nodev,noexec,relatime,nsdelegate 0 0
cgroup /sys/fs/cgroup/systemd cgroup rw,seclabel,nosuid,nodev,noexec,relatime,xattr,name=systemd 0 0
pstore /sys/fs/pstore pstore rw,seclabel,nosuid,nodev,noexec,relatime 0 0
efivarfs /sys/firmware/efi/efivars efivarfs rw,nosuid,nodev,noexec,relatime 0 0
bpf /sys/fs/bpf bpf rw,nosuid,nodev,noexec,relatime,mode=700 0 0
cgroup /sys/fs/cgroup/memory cgroup rw,seclabel,nosuid,nodev,noexec,relatime,memory 0 0
cgroup /sys/fs/cgroup/cpu,cpuacct cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpu,cpuacct 0 0
cgroup /sys/fs/cgroup/perf_event cgroup rw,seclabel,nosuid,nodev,noexec,relatime,perf_event 0 0
cgroup /sys/fs/cgroup/hugetlb cgroup rw,seclabel,nosuid,nodev,noexec,relatime,hugetlb 0 0
cgroup /sys/fs/cgroup/blkio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,blkio 0 0
cgroup /sys/fs/cgroup/devices cgroup rw,seclabel,nosuid,nodev,noexec,relatime,devices 0 0
cgroup /sys/fs/cgroup/pids cgroup rw,seclabel,nosuid,nodev,noexec,relatime,pids 0 0
cgroup /sys/fs/cgroup/net_cls,net_prio cgroup rw,seclabel,nosuid,nodev,noexec,relatime,net_cls,net_prio 0 0
cgroup /sys/fs/cgroup/cpuset cgroup rw,seclabel,nosuid,nodev,noexec,relatime,cpuset 0 0
cgroup /sys/fs/cgroup/freezer cgroup rw,seclabel,nosuid,nodev,noexec,relatime,freezer 0 0
configfs /sys/kernel/config configfs rw,relatime 0 0
/dev/sda5 /sysroot btrfs ro,seclabel,relatime,space_cache,subvolid=256,subvol=/system 0 0
/dev/sda5 / btrfs ro,seclabel,relatime,space_cache,subvolid=256,subvol=/system/ostree/deploy/fedora/deploy/f73012a35a12a34c6f05b78c46df8709f33e4fdbccfad8bdd5fafd0914298266.0 0 0
/dev/sda5 /usr btrfs ro,seclabel,relatime,space_cache,subvolid=256,subvol=/system/ostree/deploy/fedora/deploy/f73012a35a12a34c6f05b78c46df8709f33e4fdbccfad8bdd5fafd0914298266.0/usr 0 0
selinuxfs /sys/fs/selinux selinuxfs rw,relatime 0 0
+ '[' '!' -f /run/ostree-live ']'
+ add_wants boot.mount
+ local name=boot.mount
+ shift
+ local wants_dir=/run/systemd/generator/local-fs.target.wants
+ mkdir -p /run/systemd/generator/local-fs.target.wants
+ ln -sf ../boot.mount /run/systemd/generator/local-fs.target.wants/boot.mount
+ cat
/usr/lib/systemd/system-generators/coreos-boot-mount-generator: line 20: cannot create temp file for here-document: Read-only file system
```

I didn't know shell here documents required temporary files, but apparently they do and it makes the generator fail. I found some reference about that here: https://www.oilshell.org/blog/2016/10/18.html and https://github.com/bminor/bash/blob/d233b485e83c3a784b803fb894280773f16f2deb/redir.c#L452

As you can see `/tmp` is not yet mounted, and the shell script is probably failing because of that.

A workaround is to set at the top of the generator:
```
TMPDIR=$UNIT_DIR
```

With this fix, now the boot continues (but fails later on because /boot/efi fails because the partition does not have the right label). may I suggest that the generator should also read /etc/fstab in case `/boot` and `/boot/efi` are specified, and if they are specified, it should not generate the units...

Note: generator documentation suggest writing generators in C (however this would have made this issue harder to understand): https://www.freedesktop.org/software/systemd/man/systemd.generator.html

**Comment by jlebon** [comment]
> This is probably an unsupported migration path, but I have a system that was running fedora silverblue, planning to rebase it to fedora coreos afterwards. I rebased it today and I have issues with /boot not mounting properly.

I think in theory FAH/Silverblue could be migrated to FCOS, but it's unlikely we will develop much tooling to make that easier. So yeah, probably not a supported migration path. :)

The partitioning is different and a lot of booting implementation details are different. There's also various dependencies between the source configs (this repo) and [coreos-assembler](https://github.com/coreos/coreos-assembler), which would just be missed if you rebase from an Anaconda-based system. You really want to be in a supported known starting state so that automatic updates are reliable.

Specifically to the problem you're seeing though, I'm not sure offhand why there are different behaviours around `/tmp` between the two. They both use [`tmp-is-dir`](https://rpm-ostree.readthedocs.io/en/latest/manual/treefile/) nowadays so `/tmp` should definitely exist in early boot.

**Comment by dustymabe** [comment]
Thanks @mildred for the report. Since this is an unsupported migration path I'm going to close this out. Feel free to re-open if we think there are other bugs that are exposed here that need to be chased down.
