### ISSUE TITLE
systemd-networkd cannot be used in CoreOS

### ISSUE THREAD

**Issue by mildred** [coreos/fedora-coreos-config#244]
I'd prefer to use systemd-networkd instead of Networkmanager in a server setup.

This is made impossible by:

https://github.com/coreos/fedora-coreos-config/blob/54817dd6c2154cbedaf270690ae81bad5e14781b/manifests/fedora-coreos-base.yaml#L49-L55

Instead of removing files from installed packages, wouldn't it be possible to split the systemd package in two, and just not install systemd-networkd, so it would be possible to layer systemd-networkd manually after.

**Comment by jlebon** [comment]
See https://github.com/coreos/fedora-coreos-tracker/issues/24 for previous discussions on this topic.

> Instead of removing files from installed packages, wouldn't it be possible to split the systemd package in two, and just not install systemd-networkd, so it would be possible to layer systemd-networkd manually after.

Yeah, that'd probably work, though note this isn't just about users' choices. There's code that runs on top that need to understand the networking stack and interact with it (see e.g. https://github.com/coreos/afterburn/pull/316). So supporting systemd-networkd would also mean having to support it in those apps too.

If you don't mind, I think I'd rather close this issue so we keep the discussion in that ticket. Thanks!
