### ISSUE TITLE
Recent images dropped NetworkManager-team

### ISSUE THREAD

**Issue by martinpitt** [coreos/fedora-coreos-config#253]
In [cockpit's test VM refresh for fedora-coreos](https://github.com/cockpit-project/bots/pull/305) we noticed that recent images don't contain NetworkManager-team any more. In particular, our current image (30.20191014.1) still has it, but the refresh (31.20191127.1) does not any more.

I don't see anything in the [manifest history](https://github.com/coreos/fedora-coreos-config/blob/testing-devel/manifests/fedora-coreos-base.yaml) that explicitly refers to that.

I don't care much either way, now we just [skip the team tests](https://github.com/cockpit-project/cockpit/pull/13276), but I wanted to check  if this was by design or just by accident.

**Comment by lucab** [comment]
Thanks for the report.
I don't think we were shipping that on purpose, and I don't think we dropped it on purpose too. I feel that it may have been part of the transitive dependency set of $something, which dropped it between F30 and F31.

Unless we get actual user requests to have it (within a reasonable usecase for FCOS), I'd say we can stick with not shipping it for now.

**Comment by jlebon** [comment]
Hmm, I don't see `NetworkManager-team` in the f30 images either though:

```
[root@coreos ~]# rpm -qa | grep NetworkManager
NetworkManager-libnm-1.16.4-1.fc30.x86_64
NetworkManager-1.16.4-1.fc30.x86_64
[root@coreos ~]# rpm-ostree status -b
State: idle
AutomaticUpdates: disabled
BootedDeployment:
* ostree://fedora:fedora/x86_64/coreos/testing
                   Version: 30.20191014.0 (2019-10-15T02:57:53Z)
                    Commit: 95878636d60ef3be2a6af1588d3167f8b4426642d674074ca00ab543ba9c7833
              GPGSignature: Valid signature by F1D8EC98F241AAF20DF69420EF3C111FCFC659B9
```

Because we use lockfiles, we can also use `git log -S` to check if it ever was in FCOS:

```
$ git log -S NetworkManager-team
$
```

**Comment by cgwalters** [comment]
Thanks for the teamwork on this one!

**Comment by martinpitt** [comment]
Ah, sorry! It was pulled in by `rpm-ostree install cockpit-networkmanager`, which has a `Recommends: NetworkManager-team`. Apparently rpm-ostree install recently started to ignore Recommends? (Plausibly when FCOS moved from Fedora 30 to 31) That would be a much more serious bug indeed. But either way, this isn't a bug in the config, so let's close this. Sorry for the noise here! I'll report that to rpm-ostree instead.

**Comment by jlebon** [comment]
> Apparently rpm-ostree install recently started to ignore Recommends?

Hmm weird, I see it getting pulled in on both f30 FCOS and f31:

```
[root@coreos ~]# rpm-ostree install cockpit-networkmanager
...
Added:
  NetworkManager-team-1:1.16.4-1.fc30.x86_64
```

```
[root@coreos ~]# rpm-ostree install cockpit-networkmanager
...
Added:
  NetworkManager-team-1:1.20.8-1.fc31.x86_64
```

We do turn off weak deps now at compose time, though there's no way to turn it off at pkglayering time currently. So there might be something more subtle going on here?
