### ISSUE TITLE
s390x: ext.config.disks.lvmdevices fails ocassionally

### ISSUE THREAD

**Issue by jschintag** [coreos/fedora-coreos-config#2807]
```
22:33:11  Jan 16 21:33:04 qemu0 kola-runext-lvmdevices[2151]: + pvcreate --devicesfile= /dev/vda /dev/vdb
22:33:11  Jan 16 21:33:04 qemu0 kola-runext-lvmdevices[2153]:   Cannot use /dev/vdb: device is partitioned
22:33:11  Jan 16 21:33:06 qemu0 kola-runext-lvmdevices[2153]:   Physical volume "/dev/vda" successfully created.
```
Probable cause is that on s390x `/dev/vda` and such are not always guaranteed to be the same disk. This most likely resulted in the above example, where `/dev/vdb` is likely the root partition.

**Comment by jlebon** [comment]
Should check if there are `/dev/disk/by-*` symlinks that we could use instead. More explicitly, `additionalDisks` supports specifying a serial name, which then shows up IIRC under something like `/dev/disk/by-id/virtio-$NAME`.

**Comment by jlebon** [comment]
Should be fixed by https://github.com/coreos/fedora-coreos-config/pull/2811.
