### ISSUE TITLE
enable sshd manually

### ISSUE THREAD

**Issue by boredsquirrel** [coreos/fedora-coreos-config#2934]
[https://discussion.fedoraproject.org/t/just-a-quick-question-about-xz-and-xz-libs/111060/12](Fedora Discuss Issue)

It seems that as the base Fedora preset enables sshd, "everything" enables it too.

I think it would be better to enable it on the variants that need it, opt-in.

[See the src.fedoraproject.org PR](https://src.fedoraproject.org/rpms/fedora-release/pull-request/326)

Where would this be enabled, as there are 2 files?

**Comment by dustymabe** [comment]
even though we encourage people to bake most everything they need in their Ignition config, SSH is pretty core to people administering their systems (monitoring or logs or remote container runtime access, etc).

SSH can be disabled by people who don't need it by disabling it in the Ignition config (it will never start if you do that). It's very unlikely we would change to have it disabled by default.

**Comment by boredsquirrel** [comment]
sorry for my phrasing. I meant "enable sshd just in coreOS" opposed to how it is currently done, for all Fedora variants.

It seems only dedicated Desktop Variants have it disabled, which was shown on "Everything" which doesnt have (and will never have) a .preset file.

**Comment by dustymabe** [comment]
Since this issue is open against the fedora coreos config I'll go ahead and close it.

I can guarantee even if Fedora changes its default settings Fedora CoreOS will continue to ship with SSH enabled by default (our CI tests will fail without it) and thus you have nothing to worry about.

**Comment by boredsquirrel** [comment]
okay so if this happens keep an eye on it and add `enable sshd.service` to your file :D
