### ISSUE TITLE
Add a preset file for Fedora CoreOS in the release rpm

### ISSUE THREAD

**Issue by rfairley** [coreos/fedora-coreos-config#33]
This issue tracks moving the systemd presets FCOS needs to a proper place. Currently, FCOS writes a preset file with the needed additional presets during [post-processing of the build](https://github.com/coreos/fedora-coreos-config/blob/a733e2cfb39cfc55981ad1d37c359665aece7dd3/fedora-coreos-base.yaml#L116-L122).

The preset file would fit cleanly into `fedora-release-coreos`, named `80-coreos.preset`, analogous to how `fedora-release-workstation` contains `80-workstation.preset`.

Once the list of needed presets in FCOS stabilizes, we could open a PR to https://src.fedoraproject.org/rpms/fedora-release with the new preset file to go in `fedora-release-coreos` in Rawhide and backport to F29 (to use in testing).

cc @dustymabe @sgallagher

**Comment by sgallagher** [comment]
:+1:, this definitely belongs in `fedora-release-coreos`.

**Comment by dustymabe** [comment]
Thanks @rfairley for the well defined problem statement and eventual solution. When the list stabilizes, let's have someone go add them to the `fedora-release-coreos` rpm.

**Comment by rfairley** [comment]
Thanks @sgallagher, @dustymabe !

**Comment by rfairley** [comment]
PR to get this into Rawhide was merged: https://src.fedoraproject.org/rpms/fedora-release/pull-request/74

Should we backport this to F30 as well? Then we can use presets from `fedora-release-coreos` in the F30 preview.

**Comment by jlebon** [comment]
> Should we backport this to F30 as well?

SGTM!

**Comment by rfairley** [comment]
PR to backport to F30: https://src.fedoraproject.org/rpms/fedora-release/pull-request/79

**Comment by dustymabe** [comment]
bumped that PR since F30 is GA now

**Comment by rfairley** [comment]
Since the presets might still change (as they did in #93), we are deciding to keep the [overlay](https://github.com/coreos/fedora-coreos-config/blob/master/overlay/usr/lib/systemd/system-preset/42-coreos.preset) as a source of truth for the presets, at least until the FCOS is stable. Adding this to the FCOS stable milestone.

The preset in the fedora-release-coreos RPM will be updated to include a comment referring to the overlay as the place to configure presets.

**Comment by rfairley** [comment]
> The preset in the fedora-release-coreos RPM will be updated to include a comment referring to the overlay as the place to configure presets.

PRs for this in f31 and f30:

https://src.fedoraproject.org/rpms/fedora-release/pull-request/82
https://src.fedoraproject.org/rpms/fedora-release/pull-request/83

**Comment by jlebon** [comment]
I think in theory this would be nice to do, but in practice it's so much more practical to have presets live in this repo. Especially presets for units which live here. Presets modifying units coming from another package could be evaluated for "upstreaming" into a shared Fedora preset file.
