### ISSUE TITLE
Assumption of `/dev/disk/by-label/{boot,root}` for non-live targets

### ISSUE THREAD

**Issue by darkmuggle** [coreos/fedora-coreos-config#400]
The `coreos-boot-mount-generator` makes a broad assumption that there are devices for `boot` and `EFI-SYSTEM`. 

We use the best-practice for using systemd mount units with:
```
[Unit]
Requires=dev-disk-by\2xdlabel-boot.device
After=dev-disk-by\2xdlabel-boot.device
```
In [1]. The problem, that I traced down is that the device link is created for the simple device. Device Mapper and Raid 0 devices will need to use `dev-mapper-<name>.device`. I'm playing with [2] to ensure that we select the correct device link. 

This assumption in [3] for Ignition-Dracut is that the `ignition-diskful.target` is around finding a device with `boot`. Then [4] comes along and blindly expects `/dev/disk/by-label/root` to be ready [5].  On second boot [6] has no dependencies on the actual device being there. @cgwalters suggested that for second boot we use explicit kargs of `root=...` which could address this issue. 

In the Cloud world, these assumptions are perfectly fine. But once we break the assumption that the disk is simple (i.e. partitions on a physical disk) as is the case with bare-metal, LUKS, iSCSI, complicated disk setup via @arithx's work we need to re-jigger the `Ignition-Diskful`. 

[1] https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/systemd/system-generators/coreos-boot-mount-generator#L28-L42

[2] https://github.com/darkmuggle/fedora-coreos-config/blob/1b59759cba1468d10882ebfefc0e0e531d0bc0df/overlay.d/05core/usr/lib/systemd/system-generators/coreos-boot-mount-generator#L25-L56.

[3] https://github.com/coreos/ignition-dracut/blob/master/dracut/30ignition/ignition-generator#L55-L57

[4] https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-mount-firstboot-sysroot.service

[5] https://github.com/coreos/fedora-coreos-config/blob/testing-devel/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-mount-sysroot.sh

[6] https://github.com/coreos/ignition-dracut/blob/master/dracut/30ignition/ignition-subsequent.target

**Comment by darkmuggle** [comment]
Some nuance that we need to consider: our `*.mount` units use `systemd-fsck@.service`, which does a `BindsTo`  on the device [1]. If the device changes underneath, then the unit fails and the device is unmounted. This causes errors like:
```
ostree[40698]: error: Unexpected state: /run/ostree-booted found, but no /boot/loader directory
```

[1] https://github.com/systemd/systemd/blob/master/units/systemd-fsck%40.service.in#L14

**Comment by jlebon** [comment]
So for root, I think we're agreed having it be overridable via karg (and that actually works today already).

I can see wanting the same thing for boot on complex devices. So then our generator would just check first to see if a `boot=` karg is given and generate a boot mount from that before falling back to `/dev/disk/by-label/boot`?

**Comment by jlebon** [comment]
Colin also had an interesting idea [here]( https://github.com/coreos/fedora-coreos-tracker/issues/465#issuecomment-615286296) on finding boot from what GRUB injects already, which would be really cool. Though I'm not sure how it'd translate to complex devices (e.g. if you boot on multipath, then you might actually be booting on one of the constituent devices, right?)

**Comment by cgwalters** [comment]
Aside but I'm pretty sure
`ostree[40698]: error: Unexpected state: /run/ostree-booted found, but no /boot/loader directory` isn't related - that's in the real root (in the case you're referencing during shutdown).  The only bit of ostree-the-code that runs in the initramfs is [ostree-prepare-root.service](https://github.com/ostreedev/ostree/blob/master/src/boot/ostree-prepare-root.service).

>  On second boot [6] has no dependencies on the actual device being there. 

Sure, but that's a generic Ignition code which also needs to handle e.g. the OpenSUSE thingy.  In *this* repo we use https://github.com/coreos/fedora-coreos-config/blob/c2488212341fa3e2a3deac224c309824ab558a94/overlay.d/05core/usr/lib/dracut/modules.d/40ignition-ostree/ignition-ostree-mount-subsequent-sysroot.service#L13
which definitely has the requires, right?

> @cgwalters suggested that for second boot we use explicit kargs of root=... which could address this issue.

Right, I think that's the simplest and even more importantly - it's basically the *default* for how most Linux systems work.  It's definitely what Anaconda ends up using for example.  We'd just be using labels to bootstrap.

**Comment by cgwalters** [comment]
> Sure, but that's a generic Ignition code which also needs to handle e.g. the OpenSUSE thingy. 

I said this somewhere else but it is for sure actively mind-melting that we need to handle and consider:

- FCOS using *both* Ignition and OSTree
- Silverblue/(older FIoT and others) using OSTree but *not* Ignition
- [OpenSuse MicroOS](https://en.opensuse.org/Kubic:MicroOS#Configuration) using Ignition but *not* OSTree
- A whole lot of other distributions (traditional Fedora/RHEL etc.) using *neither*

**Comment by darkmuggle** [comment]
> I said this somewhere else but it is for sure actively mind-melting

You have no idea :)

**Comment by cgwalters** [comment]
I think this is basically fixed, for complex root we inject `root=` nowadays.
