### ISSUE TITLE
Enable initramfs networking only on first boot

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-config#43]
We currently pass `ip=dhcp rd.neednet=1` on the kernel command line, which enables initramfs networking on every boot.  Once https://github.com/coreos/fedora-coreos-tracker/issues/24 is implemented, arrange to start networking only when Ignition will run.

**Comment by cgwalters** [comment]
I think I floated this somewhere but basically; why not have Ignition decide to enable networking itself?

**Comment by bgilbert** [comment]
@cgwalters

Upsides I can see:
- On hypervisors (QEMU, VMware, presumably VirtualBox), we wouldn't need to start initramfs networking unless there's an `ignition.config.url` parameter or a config specifying a remote URL.  This might help in environments that don't have functioning DHCP.

Downsides:
- On affected platforms, the machine would conditionally DHCP depending on whether the config had a URL in it.  That seems nonintuitive.
- Clouds and bare metal pretty much always need networking for Ignition, so conditionalizing doesn't seem to gain us anything.
- Ignition tries to be distro-independent, and networking is distro-dependent.  We could have an abstraction mechanism, but that seems messy.
- coreos-cloudinit taught us to be wary of services starting other services behind the back of systemd's dependency resolution mechanism.

So it doesn't seem worth it?

**Comment by cgwalters** [comment]
For a quick short term hack, something like
```
diff --git a/grub/02_ignition_firstboot b/grub/02_ignition_firstboot
index a154918..b4e926d 100755
--- a/grub/02_ignition_firstboot
+++ b/grub/02_ignition_firstboot
@@ -9,5 +9,5 @@ search --set=bootpart --label boot
 # to be used later on the kernel command line.
 set ignition_firstboot=""
 if [ -f "(${bootpart})/ignition.firstboot" ]; then
-    set ignition_firstboot="ignition.firstboot"
+    set ignition_firstboot="ignition.firstboot rd.neednet=1 ip=dhcp"
 fi
```

And drop the `rd.neednet=1 ip=dhcp` from the default coreos-assembler generated kargs?

**Comment by bgilbert** [comment]
@cgwalters SGTM.

**Comment by cgwalters** [comment]
@bgilbert Thanks, working on the patch now.  But would you mind briefly explaining how this works in CL today?  What is FCOS doing differently here?

**Comment by cgwalters** [comment]
https://github.com/coreos/ignition-dracut/pull/57

**Comment by bgilbert** [comment]
@cgwalters In CL, the Ignition units [pull in networkd](https://github.com/coreos/bootengine/blob/107ce54747f739dad4b56f9753852341bb759a4d/dracut/30ignition/ignition-disks.service#L11-L17).  That works because the Ignition units are conditionally enabled by `ignition-generator`.  We should do something equivalent once coreos/fedora-coreos-tracker#24 is decided.

**Comment by laenion** [comment]
The recent merge look really good to me!

Just one note regarding the networkd dependency: It would be great if network availability would stay a neutral dependency, allowing other ways to configure the network (using wicked in our case). If __systemd-networkd__ continues to be a __Wants__ requirement like in CL this won't be a problem, we can just continue appending `rd.neednet` to the options line then.

**Comment by bgilbert** [comment]
This was fixed in https://github.com/coreos/ignition-dracut/pull/57; closing.
