### ISSUE TITLE
interactive live ISO experience no longer works with Ignition 2.4.0

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-config#514]
In the new Ignition we now default to writing out a config even if once wasn't provided by the user (https://github.com/coreos/ignition/pull/1002). This breaks our [hacky detection of if an Ignition config was provided](https://github.com/coreos/fedora-coreos-config/blob/88bc228f0d098d72acc6e30504e2e7460e61ff5a/overlay.d/05core/usr/lib/systemd/system-generators/coreos-liveiso-autologin-generator#L101-L106) for the ISO boot and causes the "interactive Live ISO" experience to not happen. We need to come up with a new way for us to properly detect this so we can not have a regression.

**Comment by dustymabe** [comment]
cc @bgilbert. We should get this fixed before the testing release.

**Comment by dustymabe** [comment]
One suggestion was to use the structured journal messages ignition logs now but that gets tricky because we're running in a generator. Obviously one solution may be to hoist this stuff into a different place so we don't have that limitation.

**Comment by arithx** [comment]
Whoops, didn't catch that implication when writing the PR sorry.

One alternative could be to temporarily have Ignition write out a separate file indicating that there was no user configuration. Or we could have a fetch-style stage that could exit depending on whether or not there is a provider / user config defined which we could call in the detection script.

**Comment by cgwalters** [comment]
> One suggestion was to use the structured journal messages ignition logs now but that gets tricky because we're running in a generator.

What's tricky about querying the journal from a generator? 

(The reason this works is because this generator is running in the real root, Ignition runs in the initrd, so it's not going to race or anything)

**Comment by jlebon** [comment]
Folded a fix for this into #426.

**Comment by jlebon** [comment]
One thing related to this is that we should fix (or check if it's already fixed by the recent work to close races) the `iso-live-login` scenario in `testiso` and turn that on in CI for this repo (and really, all the default `testiso` scenarios).

**Comment by dustymabe** [comment]
> Folded a fix for this into #426.

Thanks @jlebon 

> > One suggestion was to use the structured journal messages ignition logs now but that gets tricky because we're running in a generator.
> 
> What's tricky about querying the journal from a generator?

I just wasn't sure if it would work or not, or cause other problems. Looks like it works 🎉
