### ISSUE TITLE
isolinux/syslinux is x86_64-only

### ISSUE THREAD

**Issue by r4f4** [coreos/fedora-coreos-config#53]
Commit 7c4104c6f94b50890ae76913a88d08ced0e27cf0 introduced some `isolinux` files but bear in mind that only grub is available to other arches.

**Comment by dustymabe** [comment]
@r4f4 - can you help us set things up to use grub instead for the ISO?

**Comment by dustymabe** [comment]
If you could enumerate the changes we'd need to make then it should make things easier to knock out.

**Comment by r4f4** [comment]
@ausil might also help enumerating the changes needed.

**Comment by dustymabe** [comment]
@r4f4 - Since pxelinux is part of syslinux, do you know how other architectures are pxe booted? Do they use pxelinux?

**Comment by ausil** [comment]
@dustymabe in the dhcp server you set the filename to shim.efi or grubaa64.efi
along the lines of https://docs.fedoraproject.org/en-US/Fedora/26/html/Installation_Guide/pxe-dhcpd.html which has an example for x86 uefi and x86 bios. I am not sure if you can use grub in the bios case

**Comment by r4f4** [comment]
> If you could enumerate the changes we'd need to make then it should make things easier to knock out.

So for EFI booting in `aarch64`/`x86_64` we need:
 - grub efi binary: `grubx64.efi`, `grubaa64.efi`
 - `shimx64.efi`/`shimaa64.efi`: for pxe boot
 - `grub.cfg` containing the boot entry menu. We might want a handmade one instead of the auto-generated
 - `BOOTX64.CSV`/`BOOTAA64.CSV`: used by the firmware to get the boot entry
 - `efiboot.img`: vfat filesystem
 - arguments to `genisoimage`: `-eltorito-alt-boot -e efiboot.img -no-emul-boot`

For `ppc64le`, `lorax`/`pungi` is passing the following arguments to `genisoimage`: `-r -l -sysid 'PPC' -chrp-boot`. I'm not sure what else is needed there.

Changes to how the image is generated would go to `cosa/src/cmd-buildextend-installer` with the `grub.cfg` going to the `fedora-coreos-config/installer` .

Did I miss anything? @dustymabe @ausil

**Comment by r4f4** [comment]
Using the changes in https://github.com/coreos/coreos-assembler/pull/393 and the introduced `grub.cfg` with the change mentioned in #63, I'm able to create an ISO installer for `aarch64`. So I guess this issue is resolved?

**Comment by dustymabe** [comment]
Let's mark this resolved when https://github.com/coreos/coreos-assembler/pull/393 is merged and #63 is fixed and we get a build out :)

**Comment by dustymabe** [comment]
All of these are done now \o/!
