### ISSUE TITLE
Example config for encrypted root

### ISSUE THREAD

**Issue by martin-v** [coreos/fedora-coreos-config#614]
After reading https://github.com/coreos/fedora-coreos-tracker/issues/94 (especially https://github.com/coreos/fedora-coreos-tracker/issues/94#issuecomment-535042584) and #503 correctly it should be now possible to encrypt the root system, is this correct? 

If yes, I don't understand how to configure it, can you provide an example config?

If not, is it possible implement this feature?

Thanks for your work!

**Comment by jlebon** [comment]
It's not fully enabled yet. It needs https://github.com/coreos/fedora-coreos-config/pull/609. You can see what a sample config will look like there.

**Comment by martin-v** [comment]
Great, thx!

**Comment by arithx** [comment]
https://github.com/coreos/fedora-coreos-docs/pull/172 as well
