### ISSUE TITLE
failed adding package

### ISSUE THREAD

**Issue by zhouji3x** [coreos/fedora-coreos-config#678]
I followed https://github.com/coreos/coreos-assembler/blob/master/docs/building-fcos.md and build success
I would like to add rkt package,   I found rkt on https://fedora.pkgs.org/32/fedora-x86_64/rkt-1.30.0-3.20190512git0c87656.fc32.x86_64.rpm.html,   and  added the following lines to manifest-lock.x86_64.json

    "rtk": {
      "evra": "1.30.0-3.20190512git0c87656.fc32.x86_64"
    },

it result in failure in step "cosa fetch",  error message:

error: Couldn't find locked package 'rtk-1.30.0-3.20190512git0c87656.fc32.x86_64' (pkgs matching NEVRA: 0; mismatched checksums: 0)

My question is:  where can I found packages for FCOS?

Thanks

**Comment by cgwalters** [comment]
See https://github.com/coreos/fedora-coreos-config/blob/testing-devel/README.md#adding-packages-to-the-os
