### ISSUE TITLE
bootupd v 1.3-2 broke builds

### ISSUE THREAD

**Issue by darkmuggle** [coreos/fedora-coreos-config#714]
Latest version of `bootupd` is erroring on builds:
```
+ test -d /tmp/rootfs/ostree/deploy/fedora-coreos/deploy/d57c6a71d779f5ae28d46e61bcfe9d8654fecab77ae9f913395d80ebbc4ce8bf.0/usr/lib/bootupd/updates
+ /usr/bin/bootupctl backend install --src-root=/tmp/rootfs/ostree/deploy/fedora-coreos/deploy/d57c6a71d779f5ae28d46e61bcfe9d8654fecab77ae9f913395d80ebbc4ce8bf.0 /tmp/rootfs
error: boot data installation failed: trailing input at line 1 column 35
+ rm -rf /srv/tmp/build.qemu/supermin.out /srv/tmp/build.qemu/supermin.prepare /srv/tmp/build.qemu/supermin.build
```

This has been observed in CI and locally.

[1] https://koji.fedoraproject.org/koji/buildinfo?buildID=1624886

**Comment by cgwalters** [comment]
Which build?  Isn't this a dup of what we debugged yesterday in https://github.com/coreos/coreos-assembler/pull/1809 ?

**Comment by cgwalters** [comment]
Have you updated both cosa and your fedora-coreos-config branch?

**Comment by darkmuggle** [comment]
@ravanelli do you have a link hand?

**Comment by cgwalters** [comment]
If this is an outstanding PR it will need to be rebased to pick up the fixes.

**Comment by darkmuggle** [comment]
Indeed, this was a false alarm -- updating my container fixed the problem. 

Thank you @cgwalters for the quick response.
