### ISSUE TITLE
bridge-utils is deprecated!

### ISSUE THREAD

**Issue by sghosh151** [coreos/fedora-coreos-config#86]
#Networking is including bridge-utils which has been marked as deprecated 3+years ago. Do we really want to carry this forward on a new OS build?

https://lwn.net/Articles/703776/

**Comment by cgwalters** [comment]
I think we cargo culted this from Fedora Atomic Host which had it because some Kubernetes networking containers needed it.  That may no longer be true though.

**Comment by dustymabe** [comment]
should we try to remove it now? pretty easy to add it back in FCOS if we do need it
